### ISSUE TITLE
Cache İsiuse With Master Branch 

### ISSUE THREAD

**Issue by SadMap** [AngeloCore/discord-buttons#32] opened 2021-05-29 07:23 UTC
Discord.js doesn't cache all guild members in master and because of this, the lib returns null on clicker.user and clicker.member
The Member And User Should be fetched

**Comment by xHyroM** [comment] 2021-05-29 16:25
``await button.clicker.user`` try

**Comment by c43721** [comment] 2021-05-30 21:30
Issue seems to stem with 

```js
  if (this.guild) {
  this.clicker.member = this.guild.members.resolve(data.member.user.id);
  this.clicker.user = this.client.users.resolve(data.member.user.id);
  } else {
  this.clicker.user = this.client.users.resolve(data.user.id);
  }
```

where `.resolve()` will take from cache. This should be converted to a fetch or perhaps allow clients to access `data.member.[member, user].id`?

If you fetch all members, this works as intended, but you'll need access to privledged intents to do this, not something I want to do.

**Comment by BliiTzZ** [comment] 2021-05-31 13:41
This will be fixed in a future update

**Comment by AngeloCore** [comment] 2021-05-31 20:32
Fixed!

**Closed by AngeloCore** 2021-05-31 20:32 UTC
