### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'MessageButton' of undefined

### ISSUE THREAD

**Issue by Marveryk** [AngeloCore/discord-buttons#63] opened 2021-06-01 23:39 UTC
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'MessageButton' of undefined 

It gives this error

**Comment by AngeloCore** [comment] 2021-06-03 18:36
Duplicate of #62

**Closed by AngeloCore** 2021-06-03 18:36 UTC
